### ISSUE TITLE
Changing color in Sketchup is not picked up by the Materials tab

### ISSUE THREAD

**Issue by mobilarte** [lairdubois/lairdubois-toolbox-sketchup-plugin#16] opened 2017-01-20 04:59 UTC
When changing the color of a material and refreshing the Materials tab, the icon is not changing. The thumbnail file in the temp directory `... Temp\ladb_toolbox\material_thumbnails\... ` is changed, but only closing the plugin window and reopening will refresh the icon.

Deleting the thumbnail on refresh and recreating it does not fix the problem.

**Comment by bbeaulant** [comment] 2017-01-20 10:06
What is the "icon" for you ?

**Comment by mobilarte** [comment] 2017-01-20 12:09
the icon is the png image produced by material.write_thumbnail in the materials_controller.rb. When you change its color in Sketchup, refresh the Materials tab => it still has the old color.

**Comment by bbeaulant** [comment] 2017-01-20 12:33
Ok, the "thumbnail" ;)
I think the problem is that the generated PNG file has the same name after an update. And the first load is certainly cached.

**Comment by bbeaulant** [comment] 2017-01-20 12:37
Fixed by https://github.com/lairdubois/lairdubois-toolbox-sketchup-plugin/commit/ec96714f825afca036ebfce35018c202d02afdfd
But it now tmp folder can container a lot of more files ! It can be a problem.

**Closed by bbeaulant** 2017-01-20 12:37 UTC

**Comment by bbeaulant** [comment] 2017-01-20 12:46
After a little reflexion remove previous tmp material_thumbnails dir before is a good solution. https://github.com/lairdubois/lairdubois-toolbox-sketchup-plugin/commit/85dfff0568a8d56f02dc9e1dbd207aaffbe81a94
